# Generated by Django 5.0.4 on 2024-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
